# version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    #   - ./postgresql.conf:/etc/postgresql/postgresql.conf
    #   - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
